builds:
  - binary: mackerel-plugin-bigquery-query-result-importer
    goos:
      - linux
    goarch:
      - amd64
      - arm64
archives:
  - format: zip
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
release:
  github:
    owner: syou6162 
    name: mackerel-plugin-bigquery-query-result-importer
